//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_School_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_loans
    {
        public int id { get; set; }
        public int student_id { get; set; }
        public int book_id { get; set; }
        public System.DateTime checked_out_when { get; set; }
        public System.DateTime due_when { get; set; }
        public Nullable<System.DateTime> returned_when { get; set; }
    
        public virtual Books Books_Relation { get; set; }
        public virtual Students Students_Relation { get; set; }
    }
}
