
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Open_School_Library.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Book
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Book()
    {

        this.BookLoan = new HashSet<BookLoan>();

    }


    public int BookID { get; set; }

    public string Title { get; set; }

    public string Subtitle { get; set; }

    public string Author { get; set; }

    public int Genre { get; set; }

    public int ISBN { get; set; }

    public Nullable<int> Dewey { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BookLoan> BookLoan { get; set; }

    public virtual Dewey Dewey1 { get; set; }

    public virtual Genre Genre1 { get; set; }

}

}
