//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Open_School_Library.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Grade { get; set; }
        public Nullable<decimal> Fines { get; set; }
        public int StudentID { get; set; }
        public string StudentEmail { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
