
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Open_School_Library.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Student
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Student()
    {

        this.Book_Loans = new HashSet<Book_Loans>();

    }


    public int StudentID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public int Grade { get; set; }

    public Nullable<decimal> Fines { get; set; }

    public Nullable<int> IssuedID { get; set; }

    public string StudentEmail { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Book_Loans> Book_Loans { get; set; }

}

}
